
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workstocks?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: workstocks_user
    password: workstocks_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  

###############################################
########### MYUNIVAQ PROPERTIES ###############
###############################################

